### ISSUE TITLE
Move Marshalling Methods to the Utility Class

### ISSUE THREAD

**Issue by SvenEckhardt** [SENSIDL-PROJECT/SensIDL#60]
- [x] Java
- [x]  C

**Comment by max-sch** [comment]
Java marshalling-methods was moved to the java utility-class

**Comment by pawelbielski** [comment]
C Generators provide support for marshalling with JSON with the help of CCAN JSON libraries (json.c, json.h). Those libraries are free to use both in commercial and non-commercial projects and can be downloaded at any time from [ https://github.com/rustyrussell/ccan/tree/master/ccan/json](url). 

However, since for every single struct the code that that:
1. Allocates the JSON object
2. Populates it by mapping each field, one by one.
has to be generated, it is not possible to enclose all the needed marshalling methods within the one Utility file.
