### ISSUE TITLE
Bluetooth LE with GATT Profile Adjustments 

### ISSUE THREAD

**Issue by SvenEckhardt** [SENSIDL-PROJECT/SensIDL#65]
See #22: Adjust Generators and Model for the communication protocol.
Necessary Adjustments are:

- [x] **generate Methods stubs:** Methods can be declared in the grammar in the following pattern: {+-#,~,-}name(ParameterType, parameter1, ParameterType, parameter2, ...):returnType. {+-#,~,-} has the same meaning as in UML. the visibility is optional without it the method will be public

- [x] **generate Lists:** Lists can be declared in the grammar in the following pattern: name as list as DataType. DataType is either the know DataTypes (UINT8, INT8, ...) or another DataSet that was declared by the user

- [x] **use more datasets via "uses"** (see #63)

- [x] **make getter and setter excludable:** getter and setter can be made excludeable by the keyworde exclude: followed by setter, getter

**Comment by SvenEckhardt** [comment]
These Changes are all implemented in the Java Generator. The other generators still need to be changed

**Comment by pawelbielski** [comment]
1. **generate Methods stubs:** In C the visibility of fields and methods is not defined.  There are a number of techniques that can approximate a private variable, but at the cost of the code clarity.
2. **generate Lists:** Since the C language does not provide support for dynamic lists by default, the length of the list could be defined explicitly in *.sidl  file ( static list ) or a linked list could be implemented ( dynamic list ). In the second case, several extra functions have to be implemented for manipulation of the list. The functionality for the lists should be defined in order to implementd appriopriate functions.
3. **use more datasets via "uses":** Multiple  datasets have the same functionality as in Java generators. 
4. **make getter and setter excludable:** Excludable getter/setter methods have the same functionality as in Java generators.
